fix changelog in CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -58,11 +58,21 @@ jobs:
         run: |
           latest_version=$(curl -s "https://api.github.com/repos/maxisme/notifi/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
 
-          if [ -n "${{ steps.bump_version.outputs.new_tag }}" ]
+          if [[ "${{ github.ref }}" == "refs/heads/master" ]]
           then
+            if [ -z "${{ steps.bump_version.outputs.new_tag }}" ]
+            then
+              echo "missing tag"
+              exit 1
+            fi
             echo ::set-output name=VERSION::${{ steps.bump_version.outputs.new_tag }}
-          elif [ -n "${{ steps.bump_version_dev.outputs.new_tag }}" ]
+          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]
           then
+            if [ -z "${{ steps.bump_version_dev.outputs.new_tag }}" ]
+            then
+              echo "missing tag"
+              exit 1
+            fi
             echo ::set-output name=VERSION::${{ steps.bump_version_dev.outputs.new_tag }}
             latest_version=$(jq -r 'map(select(.prerelease)) | first | .tag_name' <<< $(curl -s https://api.github.com/repos/maxisme/notifi/releases))
           else
@@ -73,7 +83,7 @@ jobs:
 
           SINGLE=$(echo -ne '\u00B4\u2018\u2019')
           DOUBLE=$(echo -ne '\u201C\u201D')
-          changelog=$(git log --pretty=format:"* %s" "HEAD...$latest_version" | awk '{print tolower($0)}' | sed "s/[$SINGLE]/'/g; s/[$DOUBLE]/\"/g" | uniq)
+          changelog=$(git log --pretty=format:"%s" "HEAD...$latest_version" | grep "resolves" | awk '{print "* " toupper( substr( $0, 1, 1 ) ) substr( $0, 2 ); }' | sed "s/[$SINGLE]/'/g; s/[$DOUBLE]/\"/g" | uniq)
           changelog="${changelog//'%'/'%25'}"
           changelog="${changelog//$'\n'/'%0A'}"
           changelog="${changelog//$'\r'/'%0D'}"
